title: "Mi GitHub Pages"
description: "Este es mi sitio web en GitHub Pages"
url: "https://tu_usuario.github.io/tu_repositorio"
baseurl: "" # Si tu sitio es subdirectorio, pon aquí el nombre del repositorio
#theme: jekyll-theme-slate # Puedes cambiar el tema aquí

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
